accounts/urls.py
from django.conf.urls import url
from accounts import views
from django.contrib.auth.views import logout

urlpatterns = [
    url(r'^login$', views.persona_login, name='persona_login'),
    url(r'^logout$', logout,{'next_page': '/'}, name='logout'),
]

lists/urls.py
from django.conf.urls import include, url
from lists import views
from lists.views import NewListView


urlpatterns = [
    url(r'^new$', NewListView.as_view(), name='new_list'),
    # url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
	# url(r'^(\d+)/add_item$', views.add_item, name='add_item'),
]

superlists/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
# from lists import views as list_views
from lists import urls as list_urls
from lists.views import HomePageView
from accounts import urls as account_urls

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    # url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
    url(r'^accounts/', include(account_urls)),
    # url(r'^admin/', include(admin.site.urls)),
]

accounts/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class User(models.Model):
	email = models.EmailField(primary_key=True)
	last_login = models.DateTimeField(default=timezone.now)
	REQUIRED_FIELDS = ()
	USERNAME_FIELD = 'email'

	def is_authenticated(self):
		return True

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

# Create your models here.
class List(models.Model):
	def get_absolute_url(self):
		return reverse('view_list', args=[self.id])
	
class Item(models.Model):
	text = models.TextField(default='')#, unique=True)
	list = models.ForeignKey(List, default=None)

	class Meta:
		# ordering = ('id',)
		unique_together = ('list', 'text')

	def __str__(self):
		return self.text

lists/forms.py
from django import forms

from lists.models import Item
from django.core.exceptions import ValidationError

EMPTY_ITEM_ERROR = "You can't have an empty list item, blin"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',                
                }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }
    
    def save(self, for_list):
        self.instance.list = for_list
        return super().save()
    # item_text = forms.CharField(
    #   widget=forms.fields.TextInput(attrs={
    #       'placeholder': 'Enter a to-do item',
    #       'class': 'form-control input-lg',
    #   }),
    # )
# class ExistingListItemForm(forms.models.ModelForm):

class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text':[DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

accounts/views.py
# from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
# Create your views here.


def persona_login(request):
    user = authenticate(assertion=request.POST['assertion'])
    if user:
        login(request, user)
    return HttpResponse('OK')


#### Spiked version of our login view:
# def persona_login(request):
#     print('login view', file=sys.stderr)
#     # user = PersonaAuthenticationBackend().authenticate(request.POST['assertion'])
#     user = authenticate(assertion = request.POST['assertion'])
#     # user = authenticate(assertion = request.POST.get('assertion'))
#     if user is not None:
#         login(request, user)
#     return redirect('/')

lists/views.py
# from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
# from django.http import HttpResponse
from lists.models import Item, List
from lists.forms import ItemForm, ExistingListItemForm
from django.views.generic import FormView, CreateView


# Create your views here.
class HomePageView(FormView):
    """docstring for HomePageView"""
    template_name = 'home.html'
    form_class = ItemForm


class NewListView(CreateView, HomePageView):

    def form_valid(self, form):
        # list_ = List.objects.create()
        # form.save(for_list=list_)
        # return redirect(list_)
        list = List.objects.create()
        Item.objects.create(text=form.cleaned_data['text'], list=list)
        return redirect('/lists/%d/' % (list.id,))


def home_page(request):
    # if request.method == 'POST':
    #   return HttpResponse(request.POST['item_text'])
    # return render(request, 'home.html')
    # return HttpResponse('<html><title>To-Do lists</title></html>')

    # if request.method == 'POST':
    #   Item.objects.create(text=request.POST['item_text'])
    #   return redirect('/lists/the-only-list-in-the-world/')
    return render(request,'home.html', {'form': ItemForm()})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    # form = ItemForm()
    form = ExistingListItemForm(for_list=list_)
    if request.method == 'POST':
        # form = ItemForm(data=request.POST)
        form = ExistingListItemForm(for_list=list_, data=request.POST)
        if form.is_valid():
            # Item.objects.create(text=request.POST['text'], list=list_)
            form.save()
            # form.save(for_list=list_)
            return redirect(list_)

    return render(request,'list.html', {'list': list_, 'form': form})


    #   try:
    #       item = Item(text = request.POST['text'], list=list_) 
    #       item.full_clean()
    #       item.save()
    #       return redirect(list_)
    #       # return redirect('/lists/%d/' % (list_.id,))
    #       # Item.objects.create(text=request.POST['item_text'], list=list_)
    #   except ValidationError:
    #       error = "You can't have an empty list item, blin"
    
    # return render(request,'list.html', {'list': list_, 'error': error, 'form': form})

def new_list(request):
    form = ItemForm(data=request.POST) #;print(request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        # Item.objects.create(text=request.POST['text'], list=list_)
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

    # list_ = List.objects.create()
    # item = Item.objects.create(text=request.POST['text'], list=list_)
    # try:
    #   item.full_clean()
    #   item.save()
    # except ValidationError:
    #   list_.delete()
    #   error = "You can't have an empty list item, blin"
    #   return render(request, 'home.html', {"error": error})
    # return redirect(list_)

    # return redirect('view_list', list_.id)
    # return redirect('/lists/%d/' % (list_.id,))

# def add_item(request, list_id):
#   list_ = List.objects.get(id=list_id)
#   Item.objects.create(text=request.POST['item_text'], list=list_)

#   return redirect('/lists/%d/' % (list_.id,))
   

lists/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>To-Do lists</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/base.css" rel="stylesheet">
</head>

    <body>
    <div class="container">

        <nav class="navbar navbar-default" role="navigation" >
            <a class="navbar-brand" href="/">Superlists</a>
        {% if user.email %}
            <a class="btn navbar-btn navbar-right" id="id_logout" href="{% url 'logout' %}">Log out</a>
            <span class="navbar-text navbar-right">Logged in as {{ user.email }}</span>
        {% else %}
            <a class="btn navbar-btn navbar-right" id="id_login" href="#">Sign in</a>
        {% endif %}
        </nav>

        <div class="row">
            <div class="col-md-6 col-md-offset-3 jumbotron">
                <div class="text-center">               
                    <h1> {% block header_text %}{% endblock header_text %} </h1>
                    <form method="POST" action="{% block form_action %}{% endblock form_action %} ">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <span class="help-block" > {{ form.text.errors }} </span>
                            </div>
                        {% endif %}
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                {% block table %}
                {% endblock table %}
            </div>
        </div>

    </div>
    <script src="http://code.jquery.com/jquery.min.js"></script>
    <script src="https://login.persona.org/include.js"></script>
    <script src="/static/accounts.js"></script>
    <script src="/static/list.js"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            var user = "{{ user.email }}" || null;
            var token = "{{ csrf_token }}";
            var urls = {
                login: "{% url 'persona_login' %}",
                // login: "TODO",
                logout: "TODO",
            };
            Superlists.Accounts.initialize(navigator, user, token, urls);
        });
    </script>
    </body>

<!--
                        <input name="item_text" id="id_new_item" 
                               placeholder="Enter a to-do item"
                               class="form-control input-lg"
                         />
-->
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list
{% endblock header_text %}

{% block form_action %} {% url 'new_list' %}
{% endblock form_action %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list
{% endblock header_text %}

{% block form_action %}{% url 'view_list' list.id %}
{% endblock form_action %}

{% block table %}
        <table id="id_list_table" class="table table-hover">
            {% for item in list.item_set.all %}
                <tr><td> {{ forloop.counter }}: {{ item.text }}</td></tr> 
            {% endfor %}
        </table>
{% endblock table %}